version: '3.8'
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:8.0.32
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8090:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge